version: "3.4"
services:
  api:
    image: ghcr.io/mrsmitty/codetocloud-source/fabrikam-api:latest
    ports:
      - "3001:3001"

  web:
    image: ghcr.io/mrsmitty/codetocloud-source/fabrikam-web:latest
    depends_on:
      - api
    environment:
      CONTENT_API_URL: http://api:3001
    ports:
      - "3000:80"